# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_qt/authorization_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(505, 391)
        Dialog.setStyleSheet(" QLineEdit {\n"
"        background-color: #FFFFFF;\n"
"        color: black;\n"
"        border: 2px solid #FEA9AB;\n"
"        border-radius: 10px;\n"
"        padding: 10px;\n"
"        font-size: 14px;\n"
"    }\n"
"\n"
"    QLineEdit:focus {\n"
"        border: 2px solid #EAB14D;\n"
"    }\n"
"\n"
"\n"
"QPushButton {\n"
"        background-color: #EAB14D;\n"
"        color: white;\n"
"        border-radius: 10px;\n"
"        padding: 8px 15px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #D89C3F;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #C68C2F;\n"
"    }")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.header_frame = QtWidgets.QFrame(Dialog)
        self.header_frame.setStyleSheet("background: rgb(254, 169, 171);\n"
"border-radius: 15px;\n"
"")
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_pixmap = QtWidgets.QLabel(self.header_frame)
        self.icon_pixmap.setMaximumSize(QtCore.QSize(48, 48))
        self.icon_pixmap.setBaseSize(QtCore.QSize(48, 48))
        self.icon_pixmap.setText("")
        self.icon_pixmap.setPixmap(QtGui.QPixmap("window_qt/../image/Черновик.ico"))
        self.icon_pixmap.setScaledContents(True)
        self.icon_pixmap.setObjectName("icon_pixmap")
        self.horizontalLayout.addWidget(self.icon_pixmap)
        self.header_label = QtWidgets.QLabel(self.header_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        self.header_label.setFont(font)
        self.header_label.setObjectName("header_label")
        self.horizontalLayout.addWidget(self.header_label)
        self.gridLayout.addWidget(self.header_frame, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout.addLayout(self.verticalLayout, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 5, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(5, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.header_label.setText(_translate("Dialog", "Черновик"))
        self.label_2.setText(_translate("Dialog", "Пароль"))
        self.label.setText(_translate("Dialog", "Логин"))
        self.pushButton_3.setText(_translate("Dialog", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
