# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_qt/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(929, 703)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("QTabWidget::pane {\n"
"        border: 1px solid #FEA9AB;\n"
"        background-color: #FFFFFF;\n"
"    }\n"
"\n"
"    QTabBar::tab {\n"
"          background-color: #FFFFFF;\n"
"        color: black;\n"
"        padding: 12px;\n"
"        border: 3px solid #EAB14D;\n"
"        border-bottom-color: #FFFFFF; /* Убираем границу снизу */\n"
"        border-top-left-radius: 5px;\n"
"        border-top-right-radius: 5px;\n"
"        margin-right: 5px;\n"
"    }\n"
"\n"
"    QTabBar::tab:selected {\n"
"        background-color: #EAB14D;\n"
"        color: white;\n"
"        border: 1px solid #EAB14D;\n"
"        border-bottom-color: #FFFFFF; /* Убираем границу снизу */\n"
"    }\n"
"\n"
"    QTabBar::tab:hover {\n"
"        background-color: #D89C3F;\n"
"        border-bottom-color: #D89C3F;\n"
"        color: white;\n"
"    }\n"
"\n"
"\n"
"QPushButton {\n"
"        background-color: #EAB14D;\n"
"        color: white;\n"
"        border-radius: 10px;\n"
"        padding: 8px 15px;\n"
"    }\n"
"    \n"
"    QPushButton:hover {\n"
"        background-color: #D89C3F;\n"
"    }\n"
"    \n"
"    QPushButton:pressed {\n"
"        background-color: #C68C2F;\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_frame = QtWidgets.QFrame(self.centralwidget)
        self.header_frame.setStyleSheet("background: rgb(254, 169, 171);\n"
"border-radius: 15px;\n"
"")
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_pixmap = QtWidgets.QLabel(self.header_frame)
        self.icon_pixmap.setMaximumSize(QtCore.QSize(48, 48))
        self.icon_pixmap.setBaseSize(QtCore.QSize(48, 48))
        self.icon_pixmap.setText("")
        self.icon_pixmap.setPixmap(QtGui.QPixmap("window_qt/../image/Черновик.ico"))
        self.icon_pixmap.setScaledContents(True)
        self.icon_pixmap.setObjectName("icon_pixmap")
        self.horizontalLayout.addWidget(self.icon_pixmap)
        self.header_label = QtWidgets.QLabel(self.header_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(24)
        self.header_label.setFont(font)
        self.header_label.setObjectName("header_label")
        self.horizontalLayout.addWidget(self.header_label)
        self.verticalLayout.addWidget(self.header_frame)
        self.tabs_widget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.tabs_widget.setFont(font)
        self.tabs_widget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabs_widget.setTabsClosable(False)
        self.tabs_widget.setMovable(False)
        self.tabs_widget.setTabBarAutoHide(False)
        self.tabs_widget.setObjectName("tabs_widget")
        self.materials = QtWidgets.QWidget()
        self.materials.setObjectName("materials")
        self.gridLayout = QtWidgets.QGridLayout(self.materials)
        self.gridLayout.setObjectName("gridLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.materials)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.tableWidget.setFont(font)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 1, 1)
        self.tabs_widget.addTab(self.materials, "")
        self.provider = QtWidgets.QWidget()
        self.provider.setObjectName("provider")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.provider)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.provider)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(14)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked)
        self.tableWidget_2.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(2)
        self.tableWidget_2.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        self.tableWidget_2.verticalHeader().setVisible(False)
        self.gridLayout_2.addWidget(self.tableWidget_2, 0, 0, 1, 1)
        self.tabs_widget.addTab(self.provider, "")
        self.verticalLayout.addWidget(self.tabs_widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabs_widget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header_label.setText(_translate("MainWindow", "Черновик"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.materials), _translate("MainWindow", "Материалы"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        self.tabs_widget.setTabText(self.tabs_widget.indexOf(self.provider), _translate("MainWindow", "Поставщики"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить"))
        self.pushButton.setText(_translate("MainWindow", "Редактирование"))
        self.pushButton_2.setText(_translate("MainWindow", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
